#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 

setxkbmap br abnt2 &
polybar &
picom --config $HOME/.config/picom/picom.conf &
xsetroot -cursor_name left_ptr &
feh --bg-scale $HOME/Imagens/Fundos/solid-color-image.jpeg &
xset s 60 &
xss-lock -l -- slock &

bspc config border_width         	2
bspc config window_gap          	12
bspc config normal_border_color		"#01796F"
bspc config focused_border_color	"#FDD700"

bspc config split_ratio          	0.52
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config single_monocle       	true

bspc rule -a Firefox desktop='^2'
